//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.Orders = new HashSet<Orders>();
        this.Visa = new HashSet<Visa>();
    }

    public string Username { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Birthdate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Orders> Orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Visa> Visa { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Product = new HashSet<Product>();
    }

    public int D_ID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Product { get; set; }
}

public partial class OrderProduct
{
    public long Id { get; set; }
    public int O_ID { get; set; }
    public int P_Code { get; set; }
    public decimal Quantity { get; set; }
}

public partial class Orders
{
    public int O_ID { get; set; }
    public string O_Date { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Username { get; set; }

    public virtual Customer Customer { get; set; }
}

public partial class Product
{
    public int P_Code { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
    public string ExpireDate { get; set; }
    public decimal Quantity { get; set; }
    public string Description { get; set; }
    public int D_ID { get; set; }

    public virtual Department Department { get; set; }
}

public partial class Visa
{
    public int V_Code { get; set; }
    public string Type { get; set; }
    public int SSN { get; set; }
    public string CardName { get; set; }
    public string Month { get; set; }
    public int Year { get; set; }
    public string Username { get; set; }

    public virtual Customer Customer { get; set; }
}
